version: '3'

services:
  elasticsearch:
    container_name: vagrant-elasticsearch
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    restart: always
    environment:
      - TZ=Asia/Hong_Kong
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx1024m
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.ml.enabled=true
      - xpack.graph.enabled=true
      - xpack.watcher.enabled=true
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"
    networks:
      - elastic
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  kibana:
    container_name: vagrant-kibana
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:7.1.1
    restart: always
    ports:
      - 5601:5601
    networks:
      - elastic
    #We don't start Kibana until the ES instance is ready
    depends_on: ['elasticsearch']
    environment:
      - TZ=Asia/Hong_Kong
      - ELASTICSEARCH_URL=http://172.23.62.92:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
  filebeat:
    container_name: vagrant-filebeat
    hostname: filebeat
    user: root
    image: docker.elastic.co/beats/filebeat:7.1.1
    restart: always
    networks:
      - elastic
    #We don't start Filebeat until the ES and Kibana instance is ready
    depends_on: ['elasticsearch','kibana']
    environment:
      - TZ=Asia/Hong_Kong
      - ELASTICSEARCH_URL=http://172.23.62.92:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    command: filebeat -e -strict.perms=false
    volumes:
      # # Mount the Filebeat configuration so users can make edits.
      # - filebeat-config:/usr/share/filebeat
      # Mount the Filebeat configuration so users can make edits.
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # Allows us to report on docker from the hosts information.
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  elasticsearch-data:
    driver: local
  # filebeat-config:
  #   driver: local

networks:
  elastic:
    driver: bridge
